name: Compile Sass

on:
  push:
    branches:
      - main # or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x' # or your preferred Ruby version
          bundler-cache: true # ensures that dependencies are cached

      - name: Install Sass
        run: gem install sass

      - name: Compile Sass
        run: sass _sass/main.scss styles.css --style=compressed

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: Compile Sass to CSS'
          file_pattern: styles.css